//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuclearWatchdog.Reactor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SWEN.755.Reactor", ConfigurationName="Reactor.IReactor")]
    public interface IReactor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SWEN.755.Reactor/IReactor/GetTemperature", ReplyAction="http://SWEN.755.Reactor/IReactor/GetTemperatureResponse")]
        int GetTemperature();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SWEN.755.Reactor/IReactor/GetTemperature", ReplyAction="http://SWEN.755.Reactor/IReactor/GetTemperatureResponse")]
        System.Threading.Tasks.Task<int> GetTemperatureAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReactorChannel : NuclearWatchdog.Reactor.IReactor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReactorClient : System.ServiceModel.ClientBase<NuclearWatchdog.Reactor.IReactor>, NuclearWatchdog.Reactor.IReactor {
        
        public ReactorClient() {
        }
        
        public ReactorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReactorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReactorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReactorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetTemperature() {
            return base.Channel.GetTemperature();
        }
        
        public System.Threading.Tasks.Task<int> GetTemperatureAsync() {
            return base.Channel.GetTemperatureAsync();
        }
    }
}
